language: java
services:
  - postgresql
sudo: systemctl start postgresql
before_script:
  - psql -c 'create database book_store;' -U postgres
  - cp config/database.yml.travis config/database.yml
addons:
  postgresql: "11.2"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433